// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/open-telemetry/opentelemetry-operator/pkg/client/versioned/typed/opentelemetry/v1alpha1"
)

type FakeOpentelemetryV1alpha1 struct {
	*testing.Fake
}

func (c *FakeOpentelemetryV1alpha1) OpenTelemetryCollectors(namespace string) v1alpha1.OpenTelemetryCollectorInterface {
	return &FakeOpenTelemetryCollectors{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOpentelemetryV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
