version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gha-docker:
        patterns:
          - "docker/*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    ignore:
      # Ignore minor version updates for kind node images
      - dependency-name: "kindest/node*"
        update-types: [ "version-update:semver-minor" ]

  - package-ecosystem: docker
    directory: /cmd/otel-allocator
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /cmd/operator-opamp-bridge
    schedule:
      interval: weekly
