version: "2"
run:
  concurrency: 3
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  # all available settings of specific linters
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/ghodss/yaml
              desc: Use sigs.k8s.io/yaml instead of github.com/ghodss/yaml
            - pkg: github.com/pkg/errors
              desc: Use 'errors' or 'fmt' instead of github.com/pkg/errors
            - pkg: go.uber.org/multierr
              desc: Use 'errors.Join' instead of go.uber.org/multierr
            - pkg: gopkg.in/yaml.v2
              desc: Use sigs.k8s.io/yaml instead of gopkg.in/yaml.v2
            - pkg: sync/atomic
              desc: Use go.uber.org/atomic instead of sync/atomic
    exhaustive:
      default-signifies-exhaustive: true
    goheader:
      template: |-
        Copyright The OpenTelemetry Authors
        SPDX-License-Identifier: Apache-2.0
    govet:
      # TODO: Enable this and fix the alignment issues.
      disable:
        - fieldalignment
      enable-all: true
      # settings per analyzer
      settings:
        printf: # analyzer name, run `go tool vet help` to see all analyzers
          funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
    importas:
      alias:
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    nolintlint:
      require-specific: true
    revive:
      confidence: 0.8
    staticcheck:
      checks:
        - all
        - -QF1008 # FIXME Omit embedded fields from selector expression
        - -QF1011 # FIXME Omit redundant type from variable declaration
        - -ST1003 # FIXME Poorly chosen identifier
        - -ST1005 # FIXME Incorrectly formatted error string
        - -ST1012 # FIXME Poorly chosen name for error variable
        - -ST1016 # FIXME Use consistent method receiver names
  enable:
    - depguard
    - errcheck
    - errorlint
    - exhaustive
    - godot
    - goheader
    - gosec
    - govet
    - importas
    - ineffassign
    - modernize
    - misspell
    - noctx
    - nolintlint
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: tests/
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-telemetry/opentelemetry-operator)
    gofmt:
      simplify: true
  exclusions:
    generated: lax
