run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  goheader:
    template-path: header.txt
  goimports:
    local-prefixes: github.com/open-telemetry/opentelemetry-operator
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  enable:
    - goheader
    - goimports
    - maligned
    - misspell
    - gosec
    - exhaustive
    - godot
    - unparam