run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  goheader:
    template-path: header.txt
  goimports:
    local-prefixes: github.com/open-telemetry/opentelemetry-operator
  maligned:
    suggest-new: true
  misspell:
    locale: US
  govet:
    disable-all: true

linters:
  enable:
    - goheader
    - goimports
    - misspell
    - gosec
    - govet
    - exhaustive
    - godot
    - unparam
    - gosimple
    - unused
    - staticcheck
    - ineffassign
    - typecheck
    - unparam