version: "2"
run:
  concurrency: 3
  issues-exit-code: 1
  tests: true

linters:
  # all available settings of specific linters
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use 'errors' or 'fmt' instead of github.com/pkg/errors
            - pkg: go.uber.org/atomic
              desc: Use sync/atomic instead of go.uber.org/atomic
            - pkg: go.uber.org/multierr
              desc: Use 'errors.Join' instead of go.uber.org/multierr
    exhaustive:
      default-signifies-exhaustive: true
    goheader:
      template: |-
        Copyright The OpenTelemetry Authors
        SPDX-License-Identifier: Apache-2.0
    govet:
      # TODO: Enable this and fix the alignment issues.
      disable:
        - fieldalignment
      enable-all: true
      # settings per analyzer
      settings:
        printf: # analyzer name, run `go tool vet help` to see all analyzers
          funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
    importas:
      alias:
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    nolintlint:
      require-specific: true
    revive:
      confidence: 0.8
      enable-all-rules: true
      enable-default-rules: true
      max-open-files: 2048
      rules:
        - name: add-constant
          disabled: true
        - name: bare-return
          disabled: true # FIXME
        - name: blank-imports
          disabled: true
        - name: context-as-argument
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: confusing-naming
          disabled: true # FIXME
        - name: confusing-results
          disabled: true # FIXME
        - name: comment-spacings
          disabled: true # FIXME
        - name: deep-exit
          disabled: true # FIXME
        - name: defer
          disabled: true # FIXME
        - name: dot-imports
          disabled: true
        - name: duplicated-imports
          disabled: true # FIXME
        - name: early-return
          disabled: true # FIXME
        - name: empty-block
          disabled: true
        - name: empty-lines
          disabled: true # FIXME
        - name: enforce-switch-style
          disabled: true # FIXME
        - name: error-naming
          disabled: true
        - name: error-strings
          disabled: true # FIXME
        - name: exported
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: get-return
          disabled: true # FIXME
        - name: identical-ifelseif-branches
          disabled: true # FIXME
        - name: identical-switch-branches
          disabled: true # FIXME
        - name: if-return
          disabled: true # FIXME
        - name: increment-decrement
          disabled: true # FIXME
        - name: import-alias-naming
          disabled: true # FIXME
        - name: import-shadowing
          disabled: true
        - name: indent-error-flow
          disabled: true # FIXME
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-directory-mismatch
          disabled: true # FIXME
        - name: receiver-naming
          disabled: true
        - name: redundant-test-main-exit
          disabled: true # FIXME
        - name: redefines-builtin-id
          disabled: true
        - name: redundant-import-alias
          disabled: true # FIXME
        - name: struct-tag
          disabled: true # FIXME
        - name: superfluous-else
          disabled: true # FIXME
        - name: unchecked-type-assertion
          disabled: true
        - name: unexported-return
          disabled: true # FIXME
        - name: unhandled-error
          disabled: true
        - name: unnecessary-stmt
          disabled: true # FIXME
        - name: unreachable-code
          disabled: true # FIXME
        - name: unsecure-url-scheme
          disabled: true
        - name: unused-parameter
          disabled: true # FIXME
        - name: unused-receiver
          disabled: true # FIXME
        - name: use-waitgroup-go
          disabled: true
        - name: var-declaration
          disabled: true # FIXME
        - name: var-naming
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1003 # FIXME Poorly chosen identifier
        - -ST1012 # FIXME Poorly chosen name for error variable
  enable:
    - depguard
    - errcheck
    - errorlint
    - exhaustive
    - godot
    - goheader
    - gosec
    - govet
    - importas
    - ineffassign
    - modernize
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: tests/
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-telemetry/opentelemetry-operator)
    gofmt:
      simplify: true
  exclusions:
    generated: lax
