# Make sure that the OT operator after upgrading itself, can upgrade the OT collectors without error.
# See issues 840 and 1117 for the bugs on upgrading OT operator.
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
crdDir: ./tests/_build/crds/
artifactsDir: ./tests/_build/artifacts/
kindContainers:
  - local/opentelemetry-operator:e2e
  - ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.49.0
commands:
  - command: make cert-manager
  - command: kubectl apply -f https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.49.0/opentelemetry-operator.yaml
  - command: kubectl rollout status -w deployment/opentelemetry-operator-controller-manager -n opentelemetry-operator-system
  - command: sleep 60
testDirs:
  - ./tests/e2e-upgrade/
timeout: 150
