# Make sure that the OT operator after upgrading itself, can upgrade the OT collectors without error.
# The test is based on the version v0.49.0, a breaking change was introduced from PR
# https://github.com/open-telemetry/opentelemetry-operator/pull/797, which added a version label "app.kubernetes.io/version",
# The version label would change between OT operator upgrade, and since at the time, the collector pod selector was the same
# as this labels, resulted in selector being modified during reconciliation which caused error due to the selector is immutable.
# Please be aware of that the collector labels are changeable in various ways, so this issue may happen in any operator < v0.52.0
# which changed the selector to be a static set of labels.
# The fix for this issue including:
# https://github.com/open-telemetry/opentelemetry-operator/issues/840, make the selector be a static set of labels;
# https://github.com/open-telemetry/opentelemetry-operator/issues/1117, delete the old collector to let the operator
# create a new one when the selector changed.
apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
  - command: kubectl apply -f ./tests/e2e-upgrade/upgrade-test/opentelemetry-operator-v0.86.0.yaml
  - command: go run hack/check-operator-ready.go
testDirs:
  - ./tests/e2e-upgrade/
timeout: 300
