apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
crdDir: ./tests/_build/crds/
artifactsDir: ./tests/_build/artifacts/
kindContainers:
- local/opentelemetry-operator:e2e
commands:
- command: make cert-manager
- command: kubectl apply -f ./tests/_build/manifests/01-opentelemetry-operator.yaml
- command: kubectl wait --timeout=5m --for=condition=available deployment opentelemetry-operator-controller-manager -n opentelemetry-operator-system
- command: sleep 5s
testDirs:
- ./tests/e2e/
