ALAUDA_OPERATOR2_TAG ?= OPENTELEMETRY-OPERATOR2-TAG-PLACEHOLDER
ALAUDA_COLLECTOR_TAG ?= OPENTELEMETRY-COLLECTOR-TAG-PLACEHOLDER

.PHONY: alauda-patch
alauda-patch:
	./hack/alauda-patch.sh "$(ALAUDA_OPERATOR2_TAG)" "$(ALAUDA_COLLECTOR_TAG)"