apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  sampler:
    type: always_on
  exporter:
    endpoint: http://otel-collector:4317
  resource:
    addK8sUIDAttributes: true # Very importyant, much WOW
  injector:
    env:
    # Required if endpoint is set to 4317.
    # Dotnet autoinstrumentation uses http/proto by default
    # See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/888e2cd216c77d12e56b54ee91dafbc4e7452a52/docs/config.md#otlp
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector:4318