apiVersion: v1
kind: Namespace
metadata:
  name: chainsaw-k8seventsreceiver

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chainsaw-k8seventsreceiver
  namespace: chainsaw-k8seventsreceiver

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chainsaw-k8seventsreceiver-role
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - quota.openshift.io
    resources:
      - clusterresourcequotas
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chainsaw-k8seventsreceiver-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chainsaw-k8seventsreceiver-role
subjects:
  - kind: ServiceAccount
    name: chainsaw-k8seventsreceiver
    namespace: chainsaw-k8seventsreceiver

---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: chainsaw-k8seventsreceiver
  namespace: chainsaw-k8seventsreceiver
spec:
  mode: deployment
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.98.0
  serviceAccount: chainsaw-k8seventsreceiver
  config: |
    receivers:
      otlp:
        protocols:
          http:
      k8s_events:
        namespaces: [chainsaw-k8seventsreceiver]
    exporters:
      debug:
        verbosity: detailed
    service:
      pipelines:
        logs:
          receivers: [k8s_events]
          exporters: [debug]
        traces:
          receivers: [otlp]
          exporters: [debug]
