apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: splunk-otel
  name: splunk-otel-operator-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: splunk-otel
    control-plane: controller-manager
status:
  loadBalancer: {}
