apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: splunk-otel
    control-plane: controller-manager
  name: splunk-otel-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app: splunk-otel
    control-plane: controller-manager
status:
  loadBalancer: {}
