apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml

# Override the TA image:
#   kustomize edit set image target-allocator=ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:v0.120.0
images:
  - name: target-allocator
    newName: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator
    newTag: latest
