# permissions for end users to view opampbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opampbridge-viewer-role
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges/status
  verbs:
  - get
