# permissions for end users to edit opampbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opampbridge-editor-role
rules:
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentelemetry.io
  resources:
  - opampbridges/status
  verbs:
  - get
