apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
    protocol: TCP
  selector:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
