# permissions for end users to view splunkotelagent.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: splunkotelagent-viewer-role
rules:
- apiGroups:
  - splunk.com
  resources:
  - splunkotelagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - splunk.com
  resources:
  - splunkotelagents/status
  verbs:
  - get
