name: Other issue
description: Create a new issue to help us improve the operator
labels: ["needs triage"]
body:
  - type: dropdown
    id: component
    attributes:
      label: Component(s)
      description: Which component(s) does your issue concern?
      multiple: true
      options:
      - collector
      - auto-instrumentation
      - target allocator
      - opamp
  - type: textarea
    attributes:
      label: Describe the issue you're reporting
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
