apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opentelemetrycollectors.opentelemetry.io
spec:
  group: opentelemetry.io
  names:
    kind: OpenTelemetryCollector
    listKind: OpenTelemetryCollectorList
    plural: opentelemetrycollectors
    shortNames:
    - otelcol
    - otelcols
    singular: opentelemetrycollector
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      description: OpenTelemetryCollector is the Schema for the opentelemetrycollectors
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OpenTelemetryCollectorSpec defines the desired state of OpenTelemetryCollector
          properties:
            args:
              additionalProperties:
                type: string
              description: Args is the set of arguments to pass to the OpenTelemetry
                Collector binary
              type: object
            config:
              description: Config is the raw JSON to be used as the collector's configuration.
                Refer to the OpenTelemetry Collector documentation for details.
              type: string
            image:
              description: Image indicates the container image to use for the OpenTelemetry
                Collector.
              type: string
            mode:
              description: Mode represents how the collector should be deployed (deployment
                vs. daemonset)
              enum:
              - daemonset
              - deployment
              type: string
            replicas:
              description: Replicas is the number of pod instances for the underlying
                OpenTelemetry Collector
              format: int32
              type: integer
            serviceAccount:
              description: ServiceAccount indicates the name of an existing service
                account to use with this instance.
              type: string
          type: object
        status:
          description: OpenTelemetryCollectorStatus defines the observed state of
            OpenTelemetryCollector
          properties:
            replicas:
              format: int32
              type: integer
            version:
              type: string
          required:
          - replicas
          - version
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
