apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opentelemetryservices.opentelemetry.io
spec:
  group: opentelemetry.io
  names:
    kind: OpenTelemetryService
    listKind: OpenTelemetryServiceList
    plural: opentelemetryservices
    shortNames:
    - otelsvc
    - otelsvcs
    singular: opentelemetryservice
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: OpenTelemetryService is the Schema for the opentelemetryservices
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenTelemetryServiceSpec defines the desired state of OpenTelemetryService
            properties:
              args:
                additionalProperties:
                  type: string
                type: object
              config:
                type: string
              image:
                type: string
              replicas:
                format: int32
                type: integer
            type: object
          status:
            description: OpenTelemetryServiceStatus defines the observed state of
              OpenTelemetryService
            properties:
              replicas:
                format: int32
                type: integer
              version:
                type: string
            required:
            - replicas
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources:
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.replicas
      status: {}
