#!/usr/bin/env bash
# Rejects edits to generated files, which must be changed via `make` targets
# instead. Intended as a pre-edit hook for AI coding harnesses.
#
# Usage: check-generated-file.sh <path-about-to-be-edited>
# Exit 0: edit is fine. Exit 1: edit must be blocked; reason is on stderr.
set -euo pipefail

path="${1:-}"
[ -n "$path" ] || exit 0

case "$path" in
  *zz_generated*.go)
    echo "BLOCKED: $path is generated by controller-gen. Edit the API types under apis/ and run 'make generate' (or 'make update')." >&2
    exit 1
    ;;
  bundle/*|*/bundle/*)
    echo "BLOCKED: bundle/ is generated by operator-sdk. Change the sources under config/ or apis/ and run 'make bundle' (or 'make update')." >&2
    exit 1
    ;;
  docs/api/*|*/docs/api/*)
    echo "BLOCKED: docs/api/ is generated by crdoc from the CRDs. Change the API types under apis/ and run 'make api-docs' (or 'make update')." >&2
    exit 1
    ;;
  CHANGELOG.md|*/CHANGELOG.md)
    echo "BLOCKED: CHANGELOG.md is assembled from .chloggen/ entries at release time and CI rejects direct edits. Add an entry with 'make chlog-new' instead." >&2
    exit 1
    ;;
esac

exit 0
