apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentelemetry-operator-prometheus
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
