apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentelemetry-operator-webhook
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/name: opentelemetry-operator
