apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"opentelemetry.io/v1alpha1","kind":"OpenTelemetryCollector","metadata":{"name":"example-opentelemetrycollector"},"spec":{"size":3}}]'
    capabilities: Basic Install
  name: opentelemetry-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Placeholder description
  displayName: Opentelemetry Operator
  install:
    spec:
      deployments:
      - name: opentelemetry-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: opentelemetry-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: opentelemetry-operator
            spec:
              containers:
              - command:
                - opentelemetry-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: opentelemetry-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: opentelemetry-operator
                resources: {}
              serviceAccountName: opentelemetry-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - opentelemetry-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - opentelemetry.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: opentelemetry-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tracing
  - distributed tracing
  - monitoring
  - troubleshooting
  maintainers:
  - email: juraci.github@kroehling.de
    name: Juraci Paixão Kröhling
  maturity: alpha
  provider:
    name: OpenTelemetry
  version: 0.0.1
