// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1

import (
	"bytes"
	"encoding/json"
	"maps"
	"regexp"
	"strconv"

	go_yaml "github.com/goccy/go-yaml"
)

type ComponentKind int

const (
	KindReceiver ComponentKind = iota
	KindExporter
	KindProcessor
	KindExtension
)

func (c ComponentKind) String() string {
	return [...]string{"receiver", "exporter", "processor", "extension"}[c]
}

// EventInfo represents an event to be recorded.
type EventInfo struct {
	Type    string
	Reason  string
	Message string
}

// AnyConfig represent parts of the config.
type AnyConfig struct {
	Object map[string]any `json:"-" yaml:",inline"`
}

// DeepCopyInto copies all properties into another AnyConfig instance.
// It performs a true deep copy by JSON round-tripping to ensure nested maps/slices
// are fully independent of the source, preventing shared-reference mutations.
func (c *AnyConfig) DeepCopyInto(out *AnyConfig) {
	*out = *c
	if c.Object != nil {
		b, err := json.Marshal(c.Object)
		if err != nil {
			// Fallback to shallow copy if JSON marshal fails.
			in, out := &c.Object, &out.Object
			*out = make(map[string]any, len(*in))
			maps.Copy((*out), *in)
			return
		}
		out.Object = make(map[string]any)
		if err = json.Unmarshal(b, &out.Object); err != nil {
			// Fallback to shallow copy if JSON unmarshal fails.
			in, out := &c.Object, &out.Object
			*out = make(map[string]any, len(*in))
			maps.Copy((*out), *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnyConfig.
func (c *AnyConfig) DeepCopy() *AnyConfig {
	if c == nil {
		return nil
	}
	out := new(AnyConfig)
	c.DeepCopyInto(out)
	return out
}

var (
	_ json.Marshaler   = &AnyConfig{}
	_ json.Unmarshaler = &AnyConfig{}
)

// UnmarshalJSON implements an alternative parser for this field.
func (c *AnyConfig) UnmarshalJSON(b []byte) error {
	vals := map[string]any{}
	if err := json.Unmarshal(b, &vals); err != nil {
		return err
	}
	c.Object = vals
	return nil
}

// MarshalJSON specifies how to convert this object into JSON.
func (c *AnyConfig) MarshalJSON() ([]byte, error) {
	if c == nil {
		return []byte("{}"), nil
	}
	return json.Marshal(c.Object)
}

// Pipeline is a struct of component type to a list of component IDs.
type Pipeline struct {
	Exporters  []string `json:"exporters" yaml:"exporters"`
	Processors []string `json:"processors,omitempty" yaml:"processors,omitempty"`
	Receivers  []string `json:"receivers" yaml:"receivers"`
}

// Config encapsulates collector config.
type Config struct {
	// +kubebuilder:pruning:PreserveUnknownFields
	Receivers AnyConfig `json:"receivers" yaml:"receivers"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Exporters AnyConfig `json:"exporters" yaml:"exporters"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Processors *AnyConfig `json:"processors,omitempty" yaml:"processors,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Connectors *AnyConfig `json:"connectors,omitempty" yaml:"connectors,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Extensions *AnyConfig `json:"extensions,omitempty" yaml:"extensions,omitempty"`
	Service    Service    `json:"service" yaml:"service"`
}

// exponentWithoutDotRegex matches integers written in exponential notation without a
// decimal point (e.g. "0e12", "1e10"). goccy/go-yaml's own number detection treats such
// strings as plain text and does not quote them, but YAML consumers that follow the
// YAML core schema (e.g. the collector's config loader) parse them back as floats.
var exponentWithoutDotRegex = regexp.MustCompile(`^[-+]?[0-9]+[eE][-+]?[0-9]+$`)

// quotedString forces goccy/go-yaml to emit the wrapped value as a quoted scalar. It is
// only ever used to wrap individual ambiguous string values (see quoteAmbiguousValues)
// rather than being registered for the whole `string` type: registering a
// go_yaml.CustomMarshaler for `string` globally was tried first, but it interferes with
// the encoder's IndentSequence(true) handling for every string, not just the ambiguous
// ones, corrupting the indentation of unrelated nested sequences (e.g. Prometheus
// receiver's static_configs/targets) elsewhere in the generated config.
type quotedString string

func (q quotedString) MarshalYAML() ([]byte, error) {
	return []byte(strconv.Quote(string(q))), nil
}

// quoteAmbiguousValues returns a copy of a decoded YAML value tree (as produced by
// AnyConfig, i.e. nested map[string]any/[]any) with string values that are ambiguous
// under the YAML core schema rewritten to quotedString, so that Yaml() emits them quoted
// and they round-trip back as strings instead of being reinterpreted as numbers
// downstream. The input tree is left untouched: Config.Object maps are shared with the
// source CR (e.g. via a shallow struct copy of Spec), so mutating them in place would
// leak into the original object.
func quoteAmbiguousValues(v any) any {
	switch val := v.(type) {
	case string:
		if exponentWithoutDotRegex.MatchString(val) {
			return quotedString(val)
		}
		return val
	case map[string]any:
		out := make(map[string]any, len(val))
		for k, elem := range val {
			out[k] = quoteAmbiguousValues(elem)
		}
		return out
	case []any:
		out := make([]any, len(val))
		for i, elem := range val {
			out[i] = quoteAmbiguousValues(elem)
		}
		return out
	default:
		return v
	}
}

// Yaml encodes the Config as a YAML string.
func (c *Config) Yaml() (string, error) {
	encodable := *c
	encodable.Receivers.Object, _ = quoteAmbiguousValues(c.Receivers.Object).(map[string]any)
	encodable.Exporters.Object, _ = quoteAmbiguousValues(c.Exporters.Object).(map[string]any)
	if c.Processors != nil {
		processors := *c.Processors
		processors.Object, _ = quoteAmbiguousValues(c.Processors.Object).(map[string]any)
		encodable.Processors = &processors
	}
	if c.Connectors != nil {
		connectors := *c.Connectors
		connectors.Object, _ = quoteAmbiguousValues(c.Connectors.Object).(map[string]any)
		encodable.Connectors = &connectors
	}
	if c.Extensions != nil {
		extensions := *c.Extensions
		extensions.Object, _ = quoteAmbiguousValues(c.Extensions.Object).(map[string]any)
		encodable.Extensions = &extensions
	}
	if c.Service.Telemetry != nil {
		telemetry := *c.Service.Telemetry
		telemetry.Object, _ = quoteAmbiguousValues(c.Service.Telemetry.Object).(map[string]any)
		encodable.Service.Telemetry = &telemetry
	}

	var buf bytes.Buffer
	yamlEncoder := go_yaml.NewEncoder(&buf, go_yaml.IndentSequence(true), go_yaml.AutoInt())
	if err := yamlEncoder.Encode(&encodable); err != nil {
		return "", err
	}
	return buf.String(), nil
}

type Service struct {
	Extensions []string `json:"extensions,omitempty" yaml:"extensions,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Telemetry *AnyConfig `json:"telemetry,omitempty" yaml:"telemetry,omitempty"`
	// +kubebuilder:pruning:PreserveUnknownFields
	Pipelines map[string]*Pipeline `json:"pipelines" yaml:"pipelines"`
}
