//go:build !ignore_autogenerated

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/autoscaling/v2"
	"k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlwaysOffSampler) DeepCopyInto(out *AlwaysOffSampler) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlwaysOffSampler.
func (in *AlwaysOffSampler) DeepCopy() *AlwaysOffSampler {
	if in == nil {
		return nil
	}
	out := new(AlwaysOffSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlwaysOnSampler) DeepCopyInto(out *AlwaysOnSampler) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlwaysOnSampler.
func (in *AlwaysOnSampler) DeepCopy() *AlwaysOnSampler {
	if in == nil {
		return nil
	}
	out := new(AlwaysOnSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeLimits) DeepCopyInto(out *AttributeLimits) {
	*out = *in
	if in.AttributeValueLengthLimit != nil {
		in, out := &in.AttributeValueLengthLimit, &out.AttributeValueLengthLimit
		*out = new(int)
		**out = **in
	}
	if in.AttributeCountLimit != nil {
		in, out := &in.AttributeCountLimit, &out.AttributeCountLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeLimits.
func (in *AttributeLimits) DeepCopy() *AttributeLimits {
	if in == nil {
		return nil
	}
	out := new(AttributeLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeNameValue) DeepCopyInto(out *AttributeNameValue) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeNameValue.
func (in *AttributeNameValue) DeepCopy() *AttributeNameValue {
	if in == nil {
		return nil
	}
	out := new(AttributeNameValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerSpec) DeepCopyInto(out *AutoscalerSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(v2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetCPUUtilization != nil {
		in, out := &in.TargetCPUUtilization, &out.TargetCPUUtilization
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemoryUtilization != nil {
		in, out := &in.TargetMemoryUtilization, &out.TargetMemoryUtilization
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerSpec.
func (in *AutoscalerSpec) DeepCopy() *AutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B3MultiPropagator) DeepCopyInto(out *B3MultiPropagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B3MultiPropagator.
func (in *B3MultiPropagator) DeepCopy() *B3MultiPropagator {
	if in == nil {
		return nil
	}
	out := new(B3MultiPropagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *B3Propagator) DeepCopyInto(out *B3Propagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new B3Propagator.
func (in *B3Propagator) DeepCopy() *B3Propagator {
	if in == nil {
		return nil
	}
	out := new(B3Propagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaggagePropagator) DeepCopyInto(out *BaggagePropagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaggagePropagator.
func (in *BaggagePropagator) DeepCopy() *BaggagePropagator {
	if in == nil {
		return nil
	}
	out := new(BaggagePropagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Base2ExponentialBucketHistogramAggregation) DeepCopyInto(out *Base2ExponentialBucketHistogramAggregation) {
	*out = *in
	if in.MaxScale != nil {
		in, out := &in.MaxScale, &out.MaxScale
		*out = new(int)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int)
		**out = **in
	}
	if in.RecordMinMax != nil {
		in, out := &in.RecordMinMax, &out.RecordMinMax
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Base2ExponentialBucketHistogramAggregation.
func (in *Base2ExponentialBucketHistogramAggregation) DeepCopy() *Base2ExponentialBucketHistogramAggregation {
	if in == nil {
		return nil
	}
	out := new(Base2ExponentialBucketHistogramAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchLogRecordProcessor) DeepCopyInto(out *BatchLogRecordProcessor) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
	if in.ScheduleDelay != nil {
		in, out := &in.ScheduleDelay, &out.ScheduleDelay
		*out = new(int)
		**out = **in
	}
	if in.ExportTimeout != nil {
		in, out := &in.ExportTimeout, &out.ExportTimeout
		*out = new(int)
		**out = **in
	}
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int)
		**out = **in
	}
	if in.MaxExportBatchSize != nil {
		in, out := &in.MaxExportBatchSize, &out.MaxExportBatchSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchLogRecordProcessor.
func (in *BatchLogRecordProcessor) DeepCopy() *BatchLogRecordProcessor {
	if in == nil {
		return nil
	}
	out := new(BatchLogRecordProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchSpanProcessor) DeepCopyInto(out *BatchSpanProcessor) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
	if in.ScheduleDelay != nil {
		in, out := &in.ScheduleDelay, &out.ScheduleDelay
		*out = new(int)
		**out = **in
	}
	if in.ExportTimeout != nil {
		in, out := &in.ExportTimeout, &out.ExportTimeout
		*out = new(int)
		**out = **in
	}
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int)
		**out = **in
	}
	if in.MaxExportBatchSize != nil {
		in, out := &in.MaxExportBatchSize, &out.MaxExportBatchSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchSpanProcessor.
func (in *BatchSpanProcessor) DeepCopy() *BatchSpanProcessor {
	if in == nil {
		return nil
	}
	out := new(BatchSpanProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	in.Receivers.DeepCopyInto(&out.Receivers)
	in.Exporters.DeepCopyInto(&out.Exporters)
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = (*in).DeepCopy()
	}
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = (*in).DeepCopy()
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = (*in).DeepCopy()
	}
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapsSpec) DeepCopyInto(out *ConfigMapsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapsSpec.
func (in *ConfigMapsSpec) DeepCopy() *ConfigMapsSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigMapsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Console) DeepCopyInto(out *Console) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Console.
func (in *Console) DeepCopy() *Console {
	if in == nil {
		return nil
	}
	out := new(Console)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAggregation) DeepCopyInto(out *DefaultAggregation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAggregation.
func (in *DefaultAggregation) DeepCopy() *DefaultAggregation {
	if in == nil {
		return nil
	}
	out := new(DefaultAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectorAttributes) DeepCopyInto(out *DetectorAttributes) {
	*out = *in
	if in.Included != nil {
		in, out := &in.Included, &out.Included
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Excluded != nil {
		in, out := &in.Excluded, &out.Excluded
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectorAttributes.
func (in *DetectorAttributes) DeepCopy() *DetectorAttributes {
	if in == nil {
		return nil
	}
	out := new(DetectorAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Detectors) DeepCopyInto(out *Detectors) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(DetectorAttributes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Detectors.
func (in *Detectors) DeepCopy() *Detectors {
	if in == nil {
		return nil
	}
	out := new(Detectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DropAggregation) DeepCopyInto(out *DropAggregation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DropAggregation.
func (in *DropAggregation) DeepCopy() *DropAggregation {
	if in == nil {
		return nil
	}
	out := new(DropAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventInfo) DeepCopyInto(out *EventInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventInfo.
func (in *EventInfo) DeepCopy() *EventInfo {
	if in == nil {
		return nil
	}
	out := new(EventInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExplicitBucketHistogramAggregation) DeepCopyInto(out *ExplicitBucketHistogramAggregation) {
	*out = *in
	if in.Boundaries != nil {
		in, out := &in.Boundaries, &out.Boundaries
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
	if in.RecordMinMax != nil {
		in, out := &in.RecordMinMax, &out.RecordMinMax
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExplicitBucketHistogramAggregation.
func (in *ExplicitBucketHistogramAggregation) DeepCopy() *ExplicitBucketHistogramAggregation {
	if in == nil {
		return nil
	}
	out := new(ExplicitBucketHistogramAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeExclude) DeepCopyInto(out *IncludeExclude) {
	*out = *in
	if in.Included != nil {
		in, out := &in.Included, &out.Included
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Excluded != nil {
		in, out := &in.Excluded, &out.Excluded
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeExclude.
func (in *IncludeExclude) DeepCopy() *IncludeExclude {
	if in == nil {
		return nil
	}
	out := new(IncludeExclude)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]networkingv1.IngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	out.Route = in.Route
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instrumentation) DeepCopyInto(out *Instrumentation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instrumentation.
func (in *Instrumentation) DeepCopy() *Instrumentation {
	if in == nil {
		return nil
	}
	out := new(Instrumentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instrumentation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationList) DeepCopyInto(out *InstrumentationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instrumentation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationList.
func (in *InstrumentationList) DeepCopy() *InstrumentationList {
	if in == nil {
		return nil
	}
	out := new(InstrumentationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstrumentationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationSpec) DeepCopyInto(out *InstrumentationSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationSpec.
func (in *InstrumentationSpec) DeepCopy() *InstrumentationSpec {
	if in == nil {
		return nil
	}
	out := new(InstrumentationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstrumentationStatus) DeepCopyInto(out *InstrumentationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstrumentationStatus.
func (in *InstrumentationStatus) DeepCopy() *InstrumentationStatus {
	if in == nil {
		return nil
	}
	out := new(InstrumentationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerPropagator) DeepCopyInto(out *JaegerPropagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerPropagator.
func (in *JaegerPropagator) DeepCopy() *JaegerPropagator {
	if in == nil {
		return nil
	}
	out := new(JaegerPropagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerRemoteSampler) DeepCopyInto(out *JaegerRemoteSampler) {
	*out = *in
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.PollingInterval != nil {
		in, out := &in.PollingInterval, &out.PollingInterval
		*out = new(int)
		**out = **in
	}
	if in.InitialSampler != nil {
		in, out := &in.InitialSampler, &out.InitialSampler
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerRemoteSampler.
func (in *JaegerRemoteSampler) DeepCopy() *JaegerRemoteSampler {
	if in == nil {
		return nil
	}
	out := new(JaegerRemoteSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastValueAggregation) DeepCopyInto(out *LastValueAggregation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastValueAggregation.
func (in *LastValueAggregation) DeepCopy() *LastValueAggregation {
	if in == nil {
		return nil
	}
	out := new(LastValueAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRecordExporter) DeepCopyInto(out *LogRecordExporter) {
	*out = *in
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLP)
		(*in).DeepCopyInto(*out)
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(Console)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRecordExporter.
func (in *LogRecordExporter) DeepCopy() *LogRecordExporter {
	if in == nil {
		return nil
	}
	out := new(LogRecordExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRecordLimits) DeepCopyInto(out *LogRecordLimits) {
	*out = *in
	if in.AttributeValueLengthLimit != nil {
		in, out := &in.AttributeValueLengthLimit, &out.AttributeValueLengthLimit
		*out = new(int)
		**out = **in
	}
	if in.AttributeCountLimit != nil {
		in, out := &in.AttributeCountLimit, &out.AttributeCountLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRecordLimits.
func (in *LogRecordLimits) DeepCopy() *LogRecordLimits {
	if in == nil {
		return nil
	}
	out := new(LogRecordLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRecordProcessor) DeepCopyInto(out *LogRecordProcessor) {
	*out = *in
	if in.Batch != nil {
		in, out := &in.Batch, &out.Batch
		*out = new(BatchLogRecordProcessor)
		(*in).DeepCopyInto(*out)
	}
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(SimpleLogRecordProcessor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRecordProcessor.
func (in *LogRecordProcessor) DeepCopy() *LogRecordProcessor {
	if in == nil {
		return nil
	}
	out := new(LogRecordProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggerProvider) DeepCopyInto(out *LoggerProvider) {
	*out = *in
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = make([]LogRecordProcessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LogRecordLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggerProvider.
func (in *LoggerProvider) DeepCopy() *LoggerProvider {
	if in == nil {
		return nil
	}
	out := new(LoggerProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterProvider) DeepCopyInto(out *MeterProvider) {
	*out = *in
	if in.Readers != nil {
		in, out := &in.Readers, &out.Readers
		*out = make([]MetricReader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Views != nil {
		in, out := &in.Views, &out.Views
		*out = make([]View, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterProvider.
func (in *MeterProvider) DeepCopy() *MeterProvider {
	if in == nil {
		return nil
	}
	out := new(MeterProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricReader) DeepCopyInto(out *MetricReader) {
	*out = *in
	if in.Pull != nil {
		in, out := &in.Pull, &out.Pull
		*out = new(PullMetricReader)
		(*in).DeepCopyInto(*out)
	}
	if in.Periodic != nil {
		in, out := &in.Periodic, &out.Periodic
		*out = new(PeriodicMetricReader)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricReader.
func (in *MetricReader) DeepCopy() *MetricReader {
	if in == nil {
		return nil
	}
	out := new(MetricReader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = new(v2.PodsMetricSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpec.
func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfigSpec) DeepCopyInto(out *MetricsConfigSpec) {
	*out = *in
	if in.ExtraLabels != nil {
		in, out := &in.ExtraLabels, &out.ExtraLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfigSpec.
func (in *MetricsConfigSpec) DeepCopy() *MetricsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NameStringValuePair) DeepCopyInto(out *NameStringValuePair) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NameStringValuePair.
func (in *NameStringValuePair) DeepCopy() *NameStringValuePair {
	if in == nil {
		return nil
	}
	out := new(NameStringValuePair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy) DeepCopyInto(out *NetworkPolicy) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy.
func (in *NetworkPolicy) DeepCopy() *NetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTLP) DeepCopyInto(out *OTLP) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(string)
		**out = **in
	}
	if in.ClientCertificate != nil {
		in, out := &in.ClientCertificate, &out.ClientCertificate
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]NameStringValuePair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HeadersList != nil {
		in, out := &in.HeadersList, &out.HeadersList
		*out = new(string)
		**out = **in
	}
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTLP.
func (in *OTLP) DeepCopy() *OTLP {
	if in == nil {
		return nil
	}
	out := new(OTLP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTLPMetric) DeepCopyInto(out *OTLPMetric) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(string)
		**out = **in
	}
	if in.ClientCertificate != nil {
		in, out := &in.ClientCertificate, &out.ClientCertificate
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]NameStringValuePair, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HeadersList != nil {
		in, out := &in.HeadersList, &out.HeadersList
		*out = new(string)
		**out = **in
	}
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.TemporalityPreference != nil {
		in, out := &in.TemporalityPreference, &out.TemporalityPreference
		*out = new(string)
		**out = **in
	}
	if in.DefaultHistogramAggregation != nil {
		in, out := &in.DefaultHistogramAggregation, &out.DefaultHistogramAggregation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTLPMetric.
func (in *OTLPMetric) DeepCopy() *OTLPMetric {
	if in == nil {
		return nil
	}
	out := new(OTLPMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTTracePropagator) DeepCopyInto(out *OTTracePropagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTTracePropagator.
func (in *OTTracePropagator) DeepCopy() *OTTracePropagator {
	if in == nil {
		return nil
	}
	out := new(OTTracePropagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftRoute) DeepCopyInto(out *OpenShiftRoute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftRoute.
func (in *OpenShiftRoute) DeepCopy() *OpenShiftRoute {
	if in == nil {
		return nil
	}
	out := new(OpenShiftRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCollector) DeepCopyInto(out *OpenTelemetryCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCollector.
func (in *OpenTelemetryCollector) DeepCopy() *OpenTelemetryCollector {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenTelemetryCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCollectorList) DeepCopyInto(out *OpenTelemetryCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenTelemetryCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCollectorList.
func (in *OpenTelemetryCollectorList) DeepCopy() *OpenTelemetryCollectorList {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenTelemetryCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCollectorSpec) DeepCopyInto(out *OpenTelemetryCollectorSpec) {
	*out = *in
	in.OpenTelemetryCommonFields.DeepCopyInto(&out.OpenTelemetryCommonFields)
	in.StatefulSetCommonFields.DeepCopyInto(&out.StatefulSetCommonFields)
	if in.Autoscaler != nil {
		in, out := &in.Autoscaler, &out.Autoscaler
		*out = new(AutoscalerSpec)
		(*in).DeepCopyInto(*out)
	}
	in.TargetAllocator.DeepCopyInto(&out.TargetAllocator)
	in.Config.DeepCopyInto(&out.Config)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(Probe)
		(*in).DeepCopyInto(*out)
	}
	in.Observability.DeepCopyInto(&out.Observability)
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]ConfigMapsSpec, len(*in))
		copy(*out, *in)
	}
	in.DaemonSetUpdateStrategy.DeepCopyInto(&out.DaemonSetUpdateStrategy)
	in.DeploymentUpdateStrategy.DeepCopyInto(&out.DeploymentUpdateStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCollectorSpec.
func (in *OpenTelemetryCollectorSpec) DeepCopy() *OpenTelemetryCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCollectorStatus) DeepCopyInto(out *OpenTelemetryCollectorStatus) {
	*out = *in
	out.Scale = in.Scale
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCollectorStatus.
func (in *OpenTelemetryCollectorStatus) DeepCopy() *OpenTelemetryCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenTelemetryCommonFields) DeepCopyInto(out *OpenTelemetryCommonFields) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PortsSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(v1.Lifecycle)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DNSPolicy != nil {
		in, out := &in.DNSPolicy, &out.DNSPolicy
		*out = new(v1.DNSPolicy)
		**out = **in
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalContainers != nil {
		in, out := &in.AdditionalContainers, &out.AdditionalContainers
		*out = make([]v1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PodDNSConfig.DeepCopyInto(&out.PodDNSConfig)
	if in.IpFamilies != nil {
		in, out := &in.IpFamilies, &out.IpFamilies
		*out = make([]v1.IPFamily, len(*in))
		copy(*out, *in)
	}
	if in.IpFamilyPolicy != nil {
		in, out := &in.IpFamilyPolicy, &out.IpFamilyPolicy
		*out = new(v1.IPFamilyPolicy)
		**out = **in
	}
	if in.TrafficDistribution != nil {
		in, out := &in.TrafficDistribution, &out.TrafficDistribution
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenTelemetryCommonFields.
func (in *OpenTelemetryCommonFields) DeepCopy() *OpenTelemetryCommonFields {
	if in == nil {
		return nil
	}
	out := new(OpenTelemetryCommonFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentBasedSampler) DeepCopyInto(out *ParentBasedSampler) {
	*out = *in
	if in.Root != nil {
		in, out := &in.Root, &out.Root
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteParentSampled != nil {
		in, out := &in.RemoteParentSampled, &out.RemoteParentSampled
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoteParentNotSampled != nil {
		in, out := &in.RemoteParentNotSampled, &out.RemoteParentNotSampled
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalParentSampled != nil {
		in, out := &in.LocalParentSampled, &out.LocalParentSampled
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalParentNotSampled != nil {
		in, out := &in.LocalParentNotSampled, &out.LocalParentNotSampled
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentBasedSampler.
func (in *ParentBasedSampler) DeepCopy() *ParentBasedSampler {
	if in == nil {
		return nil
	}
	out := new(ParentBasedSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeriodicMetricReader) DeepCopyInto(out *PeriodicMetricReader) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeriodicMetricReader.
func (in *PeriodicMetricReader) DeepCopy() *PeriodicMetricReader {
	if in == nil {
		return nil
	}
	out := new(PeriodicMetricReader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pipeline) DeepCopyInto(out *Pipeline) {
	*out = *in
	if in.Exporters != nil {
		in, out := &in.Exporters, &out.Exporters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Receivers != nil {
		in, out := &in.Receivers, &out.Receivers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pipeline.
func (in *Pipeline) DeepCopy() *Pipeline {
	if in == nil {
		return nil
	}
	out := new(Pipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudgetSpec) DeepCopyInto(out *PodDisruptionBudgetSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudgetSpec.
func (in *PodDisruptionBudgetSpec) DeepCopy() *PodDisruptionBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsSpec) DeepCopyInto(out *PortsSpec) {
	*out = *in
	in.ServicePort.DeepCopyInto(&out.ServicePort)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsSpec.
func (in *PortsSpec) DeepCopy() *PortsSpec {
	if in == nil {
		return nil
	}
	out := new(PortsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probe) DeepCopyInto(out *Probe) {
	*out = *in
	if in.InitialDelaySeconds != nil {
		in, out := &in.InitialDelaySeconds, &out.InitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		*out = new(int32)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probe.
func (in *Probe) DeepCopy() *Probe {
	if in == nil {
		return nil
	}
	out := new(Probe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prometheus) DeepCopyInto(out *Prometheus) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.WithoutUnits != nil {
		in, out := &in.WithoutUnits, &out.WithoutUnits
		*out = new(bool)
		**out = **in
	}
	if in.WithoutTypeSuffix != nil {
		in, out := &in.WithoutTypeSuffix, &out.WithoutTypeSuffix
		*out = new(bool)
		**out = **in
	}
	if in.WithoutScopeInfo != nil {
		in, out := &in.WithoutScopeInfo, &out.WithoutScopeInfo
		*out = new(bool)
		**out = **in
	}
	if in.WithResourceConstantLabels != nil {
		in, out := &in.WithResourceConstantLabels, &out.WithResourceConstantLabels
		*out = new(IncludeExclude)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prometheus.
func (in *Prometheus) DeepCopy() *Prometheus {
	if in == nil {
		return nil
	}
	out := new(Prometheus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Propagator) DeepCopyInto(out *Propagator) {
	*out = *in
	if in.Composite != nil {
		in, out := &in.Composite, &out.Composite
		*out = make([]TextMapPropagator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Propagator.
func (in *Propagator) DeepCopy() *Propagator {
	if in == nil {
		return nil
	}
	out := new(Propagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullMetricExporter) DeepCopyInto(out *PullMetricExporter) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(Prometheus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullMetricExporter.
func (in *PullMetricExporter) DeepCopy() *PullMetricExporter {
	if in == nil {
		return nil
	}
	out := new(PullMetricExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullMetricReader) DeepCopyInto(out *PullMetricReader) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullMetricReader.
func (in *PullMetricReader) DeepCopy() *PullMetricReader {
	if in == nil {
		return nil
	}
	out := new(PullMetricReader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PushMetricExporter) DeepCopyInto(out *PushMetricExporter) {
	*out = *in
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLPMetric)
		(*in).DeepCopyInto(*out)
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(Console)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PushMetricExporter.
func (in *PushMetricExporter) DeepCopy() *PushMetricExporter {
	if in == nil {
		return nil
	}
	out := new(PushMetricExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make([]AttributeNameValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttributesList != nil {
		in, out := &in.AttributesList, &out.AttributesList
		*out = new(string)
		**out = **in
	}
	if in.SchemaURL != nil {
		in, out := &in.SchemaURL, &out.SchemaURL
		*out = new(string)
		**out = **in
	}
	if in.Detectors != nil {
		in, out := &in.Detectors, &out.Detectors
		*out = new(Detectors)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDKConfig) DeepCopyInto(out *SDKConfig) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.AttributeLimits != nil {
		in, out := &in.AttributeLimits, &out.AttributeLimits
		*out = new(AttributeLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(Resource)
		(*in).DeepCopyInto(*out)
	}
	if in.Propagator != nil {
		in, out := &in.Propagator, &out.Propagator
		*out = new(Propagator)
		(*in).DeepCopyInto(*out)
	}
	if in.TracerProvider != nil {
		in, out := &in.TracerProvider, &out.TracerProvider
		*out = new(TracerProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.MeterProvider != nil {
		in, out := &in.MeterProvider, &out.MeterProvider
		*out = new(MeterProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.LoggerProvider != nil {
		in, out := &in.LoggerProvider, &out.LoggerProvider
		*out = new(LoggerProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDKConfig.
func (in *SDKConfig) DeepCopy() *SDKConfig {
	if in == nil {
		return nil
	}
	out := new(SDKConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sampler) DeepCopyInto(out *Sampler) {
	*out = *in
	if in.AlwaysOn != nil {
		in, out := &in.AlwaysOn, &out.AlwaysOn
		*out = new(AlwaysOnSampler)
		**out = **in
	}
	if in.AlwaysOff != nil {
		in, out := &in.AlwaysOff, &out.AlwaysOff
		*out = new(AlwaysOffSampler)
		**out = **in
	}
	if in.TraceIDRatioBased != nil {
		in, out := &in.TraceIDRatioBased, &out.TraceIDRatioBased
		*out = new(TraceIDRatioBasedSampler)
		(*in).DeepCopyInto(*out)
	}
	if in.ParentBased != nil {
		in, out := &in.ParentBased, &out.ParentBased
		*out = new(ParentBasedSampler)
		(*in).DeepCopyInto(*out)
	}
	if in.JaegerRemote != nil {
		in, out := &in.JaegerRemote, &out.JaegerRemote
		*out = new(JaegerRemoteSampler)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sampler.
func (in *Sampler) DeepCopy() *Sampler {
	if in == nil {
		return nil
	}
	out := new(Sampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleSubresourceStatus) DeepCopyInto(out *ScaleSubresourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleSubresourceStatus.
func (in *ScaleSubresourceStatus) DeepCopy() *ScaleSubresourceStatus {
	if in == nil {
		return nil
	}
	out := new(ScaleSubresourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = (*in).DeepCopy()
	}
	if in.Pipelines != nil {
		in, out := &in.Pipelines, &out.Pipelines
		*out = make(map[string]*Pipeline, len(*in))
		for key, val := range *in {
			var outVal *Pipeline
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Pipeline)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleLogRecordProcessor) DeepCopyInto(out *SimpleLogRecordProcessor) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleLogRecordProcessor.
func (in *SimpleLogRecordProcessor) DeepCopy() *SimpleLogRecordProcessor {
	if in == nil {
		return nil
	}
	out := new(SimpleLogRecordProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleSpanProcessor) DeepCopyInto(out *SimpleSpanProcessor) {
	*out = *in
	in.Exporter.DeepCopyInto(&out.Exporter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleSpanProcessor.
func (in *SimpleSpanProcessor) DeepCopy() *SimpleSpanProcessor {
	if in == nil {
		return nil
	}
	out := new(SimpleSpanProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanExporter) DeepCopyInto(out *SpanExporter) {
	*out = *in
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLP)
		(*in).DeepCopyInto(*out)
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(Console)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanExporter.
func (in *SpanExporter) DeepCopy() *SpanExporter {
	if in == nil {
		return nil
	}
	out := new(SpanExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanLimits) DeepCopyInto(out *SpanLimits) {
	*out = *in
	if in.AttributeValueLengthLimit != nil {
		in, out := &in.AttributeValueLengthLimit, &out.AttributeValueLengthLimit
		*out = new(int)
		**out = **in
	}
	if in.AttributeCountLimit != nil {
		in, out := &in.AttributeCountLimit, &out.AttributeCountLimit
		*out = new(int)
		**out = **in
	}
	if in.EventCountLimit != nil {
		in, out := &in.EventCountLimit, &out.EventCountLimit
		*out = new(int)
		**out = **in
	}
	if in.LinkCountLimit != nil {
		in, out := &in.LinkCountLimit, &out.LinkCountLimit
		*out = new(int)
		**out = **in
	}
	if in.EventAttributeCountLimit != nil {
		in, out := &in.EventAttributeCountLimit, &out.EventAttributeCountLimit
		*out = new(int)
		**out = **in
	}
	if in.LinkAttributeCountLimit != nil {
		in, out := &in.LinkAttributeCountLimit, &out.LinkAttributeCountLimit
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanLimits.
func (in *SpanLimits) DeepCopy() *SpanLimits {
	if in == nil {
		return nil
	}
	out := new(SpanLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanProcessor) DeepCopyInto(out *SpanProcessor) {
	*out = *in
	if in.Batch != nil {
		in, out := &in.Batch, &out.Batch
		*out = new(BatchSpanProcessor)
		(*in).DeepCopyInto(*out)
	}
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(SimpleSpanProcessor)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanProcessor.
func (in *SpanProcessor) DeepCopy() *SpanProcessor {
	if in == nil {
		return nil
	}
	out := new(SpanProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetCommonFields) DeepCopyInto(out *StatefulSetCommonFields) {
	*out = *in
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]v1.PersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PersistentVolumeClaimRetentionPolicy != nil {
		in, out := &in.PersistentVolumeClaimRetentionPolicy, &out.PersistentVolumeClaimRetentionPolicy
		*out = new(appsv1.StatefulSetPersistentVolumeClaimRetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetCommonFields.
func (in *StatefulSetCommonFields) DeepCopy() *StatefulSetCommonFields {
	if in == nil {
		return nil
	}
	out := new(StatefulSetCommonFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SumAggregation) DeepCopyInto(out *SumAggregation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SumAggregation.
func (in *SumAggregation) DeepCopy() *SumAggregation {
	if in == nil {
		return nil
	}
	out := new(SumAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetAllocatorEmbedded) DeepCopyInto(out *TargetAllocatorEmbedded) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.PrometheusCR.DeepCopyInto(&out.PrometheusCR)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Observability.DeepCopyInto(&out.Observability)
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CollectorNotReadyGracePeriod != nil {
		in, out := &in.CollectorNotReadyGracePeriod, &out.CollectorNotReadyGracePeriod
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CollectorTargetReloadInterval != nil {
		in, out := &in.CollectorTargetReloadInterval, &out.CollectorTargetReloadInterval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetAllocatorEmbedded.
func (in *TargetAllocatorEmbedded) DeepCopy() *TargetAllocatorEmbedded {
	if in == nil {
		return nil
	}
	out := new(TargetAllocatorEmbedded)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetAllocatorPrometheusCR) DeepCopyInto(out *TargetAllocatorPrometheusCR) {
	*out = *in
	if in.AllowNamespaces != nil {
		in, out := &in.AllowNamespaces, &out.AllowNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyNamespaces != nil {
		in, out := &in.DenyNamespaces, &out.DenyNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ScrapeInterval != nil {
		in, out := &in.ScrapeInterval, &out.ScrapeInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ScrapeClasses != nil {
		in, out := &in.ScrapeClasses, &out.ScrapeClasses
		*out = make([]AnyConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodMonitorSelector != nil {
		in, out := &in.PodMonitorSelector, &out.PodMonitorSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceMonitorSelector != nil {
		in, out := &in.ServiceMonitorSelector, &out.ServiceMonitorSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScrapeConfigSelector != nil {
		in, out := &in.ScrapeConfigSelector, &out.ScrapeConfigSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProbeSelector != nil {
		in, out := &in.ProbeSelector, &out.ProbeSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetAllocatorPrometheusCR.
func (in *TargetAllocatorPrometheusCR) DeepCopy() *TargetAllocatorPrometheusCR {
	if in == nil {
		return nil
	}
	out := new(TargetAllocatorPrometheusCR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Telemetry) DeepCopyInto(out *Telemetry) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Telemetry.
func (in *Telemetry) DeepCopy() *Telemetry {
	if in == nil {
		return nil
	}
	out := new(Telemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextMapPropagator) DeepCopyInto(out *TextMapPropagator) {
	*out = *in
	if in.TraceContext != nil {
		in, out := &in.TraceContext, &out.TraceContext
		*out = new(TraceContextPropagator)
		**out = **in
	}
	if in.Baggage != nil {
		in, out := &in.Baggage, &out.Baggage
		*out = new(BaggagePropagator)
		**out = **in
	}
	if in.B3 != nil {
		in, out := &in.B3, &out.B3
		*out = new(B3Propagator)
		**out = **in
	}
	if in.B3Multi != nil {
		in, out := &in.B3Multi, &out.B3Multi
		*out = new(B3MultiPropagator)
		**out = **in
	}
	if in.Jaeger != nil {
		in, out := &in.Jaeger, &out.Jaeger
		*out = new(JaegerPropagator)
		**out = **in
	}
	if in.OTTrace != nil {
		in, out := &in.OTTrace, &out.OTTrace
		*out = new(OTTracePropagator)
		**out = **in
	}
	if in.XRay != nil {
		in, out := &in.XRay, &out.XRay
		*out = new(XRayPropagator)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextMapPropagator.
func (in *TextMapPropagator) DeepCopy() *TextMapPropagator {
	if in == nil {
		return nil
	}
	out := new(TextMapPropagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceContextPropagator) DeepCopyInto(out *TraceContextPropagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceContextPropagator.
func (in *TraceContextPropagator) DeepCopy() *TraceContextPropagator {
	if in == nil {
		return nil
	}
	out := new(TraceContextPropagator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TraceIDRatioBasedSampler) DeepCopyInto(out *TraceIDRatioBasedSampler) {
	*out = *in
	if in.Ratio != nil {
		in, out := &in.Ratio, &out.Ratio
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TraceIDRatioBasedSampler.
func (in *TraceIDRatioBasedSampler) DeepCopy() *TraceIDRatioBasedSampler {
	if in == nil {
		return nil
	}
	out := new(TraceIDRatioBasedSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerProvider) DeepCopyInto(out *TracerProvider) {
	*out = *in
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = make([]SpanProcessor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(SpanLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.Sampler != nil {
		in, out := &in.Sampler, &out.Sampler
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerProvider.
func (in *TracerProvider) DeepCopy() *TracerProvider {
	if in == nil {
		return nil
	}
	out := new(TracerProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *View) DeepCopyInto(out *View) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(ViewSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Stream != nil {
		in, out := &in.Stream, &out.Stream
		*out = new(ViewStream)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new View.
func (in *View) DeepCopy() *View {
	if in == nil {
		return nil
	}
	out := new(View)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewAggregation) DeepCopyInto(out *ViewAggregation) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(DefaultAggregation)
		**out = **in
	}
	if in.Drop != nil {
		in, out := &in.Drop, &out.Drop
		*out = new(DropAggregation)
		**out = **in
	}
	if in.Sum != nil {
		in, out := &in.Sum, &out.Sum
		*out = new(SumAggregation)
		**out = **in
	}
	if in.LastValue != nil {
		in, out := &in.LastValue, &out.LastValue
		*out = new(LastValueAggregation)
		**out = **in
	}
	if in.ExplicitBucketHistogram != nil {
		in, out := &in.ExplicitBucketHistogram, &out.ExplicitBucketHistogram
		*out = new(ExplicitBucketHistogramAggregation)
		(*in).DeepCopyInto(*out)
	}
	if in.Base2ExponentialBucketHistogram != nil {
		in, out := &in.Base2ExponentialBucketHistogram, &out.Base2ExponentialBucketHistogram
		*out = new(Base2ExponentialBucketHistogramAggregation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewAggregation.
func (in *ViewAggregation) DeepCopy() *ViewAggregation {
	if in == nil {
		return nil
	}
	out := new(ViewAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewSelector) DeepCopyInto(out *ViewSelector) {
	*out = *in
	if in.InstrumentName != nil {
		in, out := &in.InstrumentName, &out.InstrumentName
		*out = new(string)
		**out = **in
	}
	if in.InstrumentType != nil {
		in, out := &in.InstrumentType, &out.InstrumentType
		*out = new(string)
		**out = **in
	}
	if in.MeterName != nil {
		in, out := &in.MeterName, &out.MeterName
		*out = new(string)
		**out = **in
	}
	if in.MeterVersion != nil {
		in, out := &in.MeterVersion, &out.MeterVersion
		*out = new(string)
		**out = **in
	}
	if in.MeterSchemaURL != nil {
		in, out := &in.MeterSchemaURL, &out.MeterSchemaURL
		*out = new(string)
		**out = **in
	}
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewSelector.
func (in *ViewSelector) DeepCopy() *ViewSelector {
	if in == nil {
		return nil
	}
	out := new(ViewSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewStream) DeepCopyInto(out *ViewStream) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.AttributeKeys != nil {
		in, out := &in.AttributeKeys, &out.AttributeKeys
		*out = new(IncludeExclude)
		(*in).DeepCopyInto(*out)
	}
	if in.Aggregation != nil {
		in, out := &in.Aggregation, &out.Aggregation
		*out = new(ViewAggregation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewStream.
func (in *ViewStream) DeepCopy() *ViewStream {
	if in == nil {
		return nil
	}
	out := new(ViewStream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XRayPropagator) DeepCopyInto(out *XRayPropagator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XRayPropagator.
func (in *XRayPropagator) DeepCopy() *XRayPropagator {
	if in == nil {
		return nil
	}
	out := new(XRayPropagator)
	in.DeepCopyInto(out)
	return out
}
