apiVersion: opentelemetry.io/v1alpha1
kind: OpAMPBridge
metadata:
  name: opampbridge-sample
spec:
  endpoint: ws://opamp-server:4320/v1/opamp
  capabilities:
    AcceptsOpAMPConnectionSettings: true
    AcceptsOtherConnectionSettings: true
    AcceptsRemoteConfig: true
    AcceptsRestartCommand: true
    ReportsEffectiveConfig: true
    ReportsHealth: true
    ReportsOwnLogs: true
    ReportsOwnMetrics: true
    ReportsOwnTraces: true
    ReportsRemoteConfig: true
    ReportsStatus: true
  componentsAllowed:
    receivers:
    - otlp
    processors:
    - memory_limiter
    exporters:
    - logging
