apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-as-daemonset
spec:
  mode: daemonset
  config: |
    receivers:
      jaeger:

    processors:
      queued-retry:

    exporters:
      logging:

    pipelines:
      traces:
        receivers: [jaeger]
        processors: [queued-retry]
        exporters: [logging]
