apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: with-volumes
spec:
  config: |
    receivers:
      jaeger:

    processors:
      queued_retry:

    exporters:
      logging:

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [queued_retry]
          exporters: [logging]

  volumeMounts:
  - mountPath: /etc/tls-certs
    name: tls-certs-volume

  volumes:
  - name: tls-certs-volume
    secret:
      secretName: tls-certs-secret
