apiVersion: v1
kind: Service
metadata:
  name: target-allocator
  labels:
    app.kubernetes.io/name: target-allocator
    app.kubernetes.io/part-of: opentelemetry-target-allocator
    app.kubernetes.io/component: target-allocator
spec:
  selector:
    app.kubernetes.io/name: target-allocator
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: http-port
