apiVersion: v1
kind: ServiceAccount
metadata:
  name: target-allocator
  labels:
    app.kubernetes.io/name: target-allocator
    app.kubernetes.io/part-of: opentelemetry-target-allocator
    app.kubernetes.io/component: target-allocator
