apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: opentelemetry-operator-metrics
  name: controller-manager-metrics-service
  namespace: system
