apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opentelemetry-operator-controller-manager
  namespace: system
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-operator
      control-plane: controller-manager
