// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Package config contains the operator's runtime configuration.
package config

import (
	"fmt"

	"github.com/goccy/go-yaml"
	corev1 "k8s.io/api/core/v1"

	"github.com/open-telemetry/opentelemetry-operator/apis/v1alpha1"
	"github.com/open-telemetry/opentelemetry-operator/internal/apiserverendpoints"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/certmanager"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/collector"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/gatewayapi"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/opampbridge"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/openshift"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/prometheus"
	autoRBAC "github.com/open-telemetry/opentelemetry-operator/internal/autodetect/rbac"
	"github.com/open-telemetry/opentelemetry-operator/internal/autodetect/targetallocator"
	"github.com/open-telemetry/opentelemetry-operator/internal/components"
	"github.com/open-telemetry/opentelemetry-operator/internal/version"
	"github.com/open-telemetry/opentelemetry-operator/pkg/constants"
)

const (
	defaultCollectorConfigMapEntry           = "collector.yaml"
	defaultTargetAllocatorConfigMapEntry     = "targetallocator.yaml"
	defaultOperatorOpAMPBridgeConfigMapEntry = "remoteconfiguration.yaml"
	defaultOpenShiftWebhookReplicas          = 2
)

type ZapConfig struct {
	MessageKey  string `yaml:"message-key" flag:"zap-message-key" env:"ZAP_MESSAGE_KEY" usage:"The message key to be used in the customized Log Encoder" group:"Logging encoder"`
	TimeKey     string `yaml:"time-key" flag:"zap-time-key" env:"ZAP_TIME_KEY" usage:"The time key to be used in the customized Log Encoder" group:"Logging encoder"`
	LevelKey    string `yaml:"level-key" flag:"zap-level-key" env:"ZAP_LEVEL_KEY" usage:"The level key to be used in the customized Log Encoder" group:"Logging encoder"`
	LevelFormat string `yaml:"level-format" flag:"zap-level-format" env:"ZAP_LEVEL_FORMAT" usage:"The level format to be used in the customized Log Encoder" group:"Logging encoder"`
}

// Config holds the static configuration for this operator.
//
// User-facing fields carry up to four tags that are the single source of truth for
// how the field is configured. A `-` value skips this mechanism.
type Config struct {
	// TargetAllocatorImage represents the flag to override the OpenTelemetry TargetAllocator container image.
	TargetAllocatorImage string `yaml:"targetallocator-image" flag:"target-allocator-image" env:"RELATED_IMAGE_TARGET_ALLOCATOR" usage:"The default OpenTelemetry target allocator image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// OperatorOpAMPBridgeImage represents the flag to override the OpAMPBridge container image.
	OperatorOpAMPBridgeImage string `yaml:"operatoropampbridge-image" flag:"operator-opamp-bridge-image" env:"RELATED_IMAGE_OPERATOR_OPAMP_BRIDGE" usage:"The default OpenTelemetry Operator OpAMP Bridge image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// AutoInstrumentationPythonImage is the OpenTelemetry Python auto-instrumentation container image.
	AutoInstrumentationPythonImage string `yaml:"auto-instrumentation-python-image" flag:"auto-instrumentation-python-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_PYTHON" usage:"The default OpenTelemetry Python instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// CollectorImage represents the flag to override the OpenTelemetry Collector container image.
	CollectorImage string `yaml:"collector-image" flag:"collector-image" env:"RELATED_IMAGE_COLLECTOR" usage:"The default OpenTelemetry collector image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// ClusterObservabilityCollectorImage is the collector image used for the agent and
	// cluster collectors generated by the ClusterObservability reconciler. It defaults to
	// the k8s distribution at the same version as CollectorImage.
	ClusterObservabilityCollectorImage string `yaml:"clusterobservability-collector-image" flag:"clusterobservability-collector-image" env:"-" usage:"The OpenTelemetry collector image used for collectors generated by the ClusterObservability reconciler. Defaults to the k8s distribution." group:"Component images"`
	// CollectorConfigMapEntry represents the configuration file name for the collector. Immutable.
	CollectorConfigMapEntry string `yaml:"collector-configmap-entry" flag:"-" env:"-" usage:"ConfigMap key for the collector configuration." group:"File-only keys"`
	// EnableMultiInstrumentation is true when the operator supports multi instrumentation.
	EnableMultiInstrumentation bool `yaml:"enable-multi-instrumentation" flag:"enable-multi-instrumentation" env:"ENABLE_MULTI_INSTRUMENTATION" usage:"Controls whether the operator supports multi instrumentation" group:"Auto-instrumentation toggles"`
	// EnableApacheHttpdAutoInstrumentation is true when the operator supports ApacheHttpd auto instrumentation.
	EnableApacheHttpdInstrumentation bool `yaml:"enable-apache-httpd-instrumentation" flag:"enable-apache-httpd-instrumentation" env:"ENABLE_APACHE_HTTPD_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports Apache HTTPD auto-instrumentation" group:"Auto-instrumentation toggles"`
	// EnableDotNetAutoInstrumentation is true when the operator supports dotnet auto instrumentation.
	EnableDotNetAutoInstrumentation bool `yaml:"enable-dot-net-auto-instrumentation" flag:"enable-dotnet-instrumentation" env:"ENABLE_DOTNET_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports dotnet auto-instrumentation" group:"Auto-instrumentation toggles"`
	// EnableGoAutoInstrumentation is true when the operator supports Go auto instrumentation.
	EnableGoAutoInstrumentation bool `yaml:"enable-go-auto-instrumentation" flag:"enable-go-instrumentation" env:"ENABLE_GO_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports Go auto-instrumentation" group:"Auto-instrumentation toggles"`
	// EnableNginxAutoInstrumentation is true when the operator supports nginx auto instrumentation.
	EnableNginxAutoInstrumentation bool `yaml:"enable-nginx-auto-instrumentation" flag:"enable-nginx-instrumentation" env:"ENABLE_NGINX_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports nginx auto-instrumentation" group:"Auto-instrumentation toggles"`
	// EnablePythonAutoInstrumentation is true when the operator supports dotnet auto instrumentation.
	EnablePythonAutoInstrumentation bool `yaml:"enable-python-auto-instrumentation" flag:"enable-python-instrumentation" env:"ENABLE_PYTHON_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports python auto-instrumentation" group:"Auto-instrumentation toggles"`
	// EnableNodeJSAutoInstrumentation is true when the operator supports dotnet auto instrumentation.
	EnableNodeJSAutoInstrumentation bool `yaml:"enable-node-js-auto-instrumentation" flag:"enable-nodejs-instrumentation" env:"ENABLE_NODEJS_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports nodejs auto-instrumentation" group:"Auto-instrumentation toggles"`
	// EnableJavaAutoInstrumentation is true when the operator supports java auto instrumentation.
	EnableJavaAutoInstrumentation bool `yaml:"enable-java-auto-instrumentation" flag:"enable-java-instrumentation" env:"ENABLE_JAVA_AUTO_INSTRUMENTATION" usage:"Controls whether the operator supports java auto-instrumentation" group:"Auto-instrumentation toggles"`
	// AutoInstrumentationDotNetImage is the OpenTelemetry DotNet auto-instrumentation container image.
	AutoInstrumentationDotNetImage string `yaml:"auto-instrumentation-dot-net-image" flag:"auto-instrumentation-dotnet-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_DOTNET" usage:"The default OpenTelemetry DotNet instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// AutoInstrumentationGoImage is the OpenTelemetry Go auto-instrumentation container image.
	AutoInstrumentationGoImage string `yaml:"auto-instrumentation-go-image" flag:"auto-instrumentation-go-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_GO" usage:"The default OpenTelemetry Go instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// AutoInstrumentationApacheHttpdImage is the OpenTelemetry ApacheHttpd auto-instrumentation container image.
	AutoInstrumentationApacheHttpdImage string `yaml:"auto-instrumentation-apache-httpd-image" flag:"auto-instrumentation-apache-httpd-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_APACHE_HTTPD" usage:"The default OpenTelemetry Apache HTTPD instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// AutoInstrumentationNginxImage is the OpenTelemetry Nginx auto-instrumentation container image.
	AutoInstrumentationNginxImage string `yaml:"auto-instrumentation-nginx-image" flag:"auto-instrumentation-nginx-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_NGINX" usage:"The default OpenTelemetry Nginx instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// TargetAllocatorConfigMapEntry represents the configuration file name for the TargetAllocator. Immutable.
	TargetAllocatorConfigMapEntry string `yaml:"target-allocator-configmap-entry" flag:"-" env:"-" usage:"ConfigMap key for the Target Allocator configuration." group:"File-only keys"`
	// OperatorOpAMPBridgeImageConfigMapEntry represents the configuration file name for the OpAMPBridge. Immutable.
	OperatorOpAMPBridgeConfigMapEntry string `yaml:"operator-op-amp-bridge-configmap-entry" flag:"-" env:"-" usage:"ConfigMap key for the OpAMP bridge configuration." group:"File-only keys"`
	// AutoInstrumentationNodeJSImage is the OpenTelemetry NodeJS auto-instrumentation container image.
	AutoInstrumentationNodeJSImage string `yaml:"auto-instrumentation-node-js-image" flag:"auto-instrumentation-nodejs-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_NODEJS" usage:"The default OpenTelemetry NodeJS instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// AutoInstrumentationJavaImage returns OpenTelemetry Java auto-instrumentation container image.
	AutoInstrumentationJavaImage string `yaml:"auto-instrumentation-java-image" flag:"auto-instrumentation-java-image" env:"RELATED_IMAGE_AUTO_INSTRUMENTATION_JAVA" usage:"The default OpenTelemetry Java instrumentation image. This image is used when no image is specified in the CustomResource." group:"Component images"`
	// OpenshiftCreateDashboard creates an OpenShift dashboard for monitoring the OpenTelemetryCollector instances
	OpenshiftCreateDashboard bool `yaml:"openshift-create-dashboard" flag:"openshift-create-dashboard" env:"OPENSHIFT_CREATE_DASHBOARD" usage:"Create an OpenShift dashboard for monitoring the OpenTelemetryCollector instances" group:"OpenShift and FIPS"`
	// OpenShiftRoutesAvailability represents the availability of the OpenShift Routes API.
	OpenShiftRoutesAvailability openshift.RoutesAvailability `yaml:"open-shift-routes-availability"`
	// GatewayAPIsAvailability represents the availability of the Gateway APIs.
	GatewayAPIsAvailability gatewayapi.ApiAvailability `yaml:"gateway-apis-availability"`
	// PrometheusCRAvailability represents the availability of the Prometheus Operator CRDs.
	PrometheusCRAvailability prometheus.Availability `yaml:"prometheus-cr-availability"`
	// CertManagerAvailability represents the availability of the Cert-Manager.
	CertManagerAvailability certmanager.Availability `yaml:"cert-manager-availability"`
	// TargetAllocatorAvailability represents the availability of the TargetAllocator CRD.
	TargetAllocatorAvailability targetallocator.Availability `yaml:"target-allocator-availability"`
	// CollectorAvailability represents the availability of the OpenTelemetryCollector CRD.
	CollectorAvailability collector.Availability `yaml:"collector-availability"`
	// OpAmpBridgeAvailability represents the availability of the OpAmpBridge CRD.
	OpAmpBridgeAvailability opampbridge.Availability `yaml:"opampbridge-availability"`
	// IgnoreMissingCollectorCRDs is true if the operator can ignore missing OpenTelemetryCollector CRDs.
	IgnoreMissingCollectorCRDs bool `yaml:"ignore-missing-collector-crds" flag:"ignore-missing-collector-crds" env:"IGNORE_MISSING_COLLECTOR_CRDS" usage:"Ignore missing OpenTelemetryCollector CRDs presence in the cluster" group:"General"`
	// LabelsFilter Returns the filters converted to regex strings used to filter out unwanted labels from propagations.
	LabelsFilter []string `yaml:"labels-filter" flag:"labels-filter" flagtype:"array" env:"LABELS_FILTER" usage:"Labels to filter away from propagating onto deploys. It should be a string array containing patterns, which are literal strings optionally containing a * wildcard character. Example: --labels-filter=.*filter.out will filter out labels that looks like: label.filter.out: true" group:"Filters"`
	// AnnotationsFilter Returns the filters converted to regex strings used to filter out unwanted labels from propagations.
	AnnotationsFilter []string `yaml:"annotations-filter" flag:"annotations-filter" flagtype:"array" env:"ANNOTATIONS_FILTER" usage:"Annotations to filter away from propagating onto deploys. It should be a string array containing patterns, which are literal strings optionally containing a * wildcard character. Example: --annotations-filter=.*filter.out will filter out annotations that looks like: annotation.filter.out: true" group:"Filters"`
	// MetricsAddr is the address the metric endpoint binds to.
	MetricsAddr string `yaml:"metrics-addr" flag:"metrics-addr" env:"METRICS_ADDR" usage:"The address the metric endpoint binds to." group:"Metrics, health, and profiling"`
	// MetricsSecure enables serving metrics via HTTPS with authentication and authorization.
	MetricsSecure bool `yaml:"metrics-secure" flag:"metrics-secure" env:"METRICS_SECURE" usage:"Enable secure serving for metrics endpoint with authentication and authorization. When enabled ano no TLS certificates are provided, the operator generates self signed certificates." group:"Metrics, health, and profiling"`
	// MetricsTLSCertFile is the TLS certificate file for the metrics server.
	MetricsTLSCertFile string `yaml:"metrics-tls-cert-file" flag:"metrics-tls-cert-file" env:"METRICS_TLS_CERT_FILE" usage:"TLS certificate file for the metrics server" group:"Metrics, health, and profiling"`
	// MetricsTLSKeyFile is the TLS private key file for the metrics server.
	MetricsTLSKeyFile string `yaml:"metrics-tls-key-file" flag:"metrics-tls-key-file" env:"METRICS_TLS_KEY_FILE" usage:"TLS private key file for the metrics server" group:"Metrics, health, and profiling"`
	// ProbeAddr is the address the probe endpoint binds to.
	ProbeAddr string `yaml:"health-probe-addr" flag:"health-probe-addr" env:"HEALTH_PROBE_ADDR" usage:"The address the probe endpoint binds to." group:"Metrics, health, and profiling"`
	// PprofAddr is the address to expose the pprof server. Default is empty string which disables the pprof server.
	PprofAddr string `yaml:"pprof-addr" flag:"pprof-addr" env:"PPROF_ADDR" usage:"The address to expose the pprof server. Default is empty string which disables the pprof server." group:"Metrics, health, and profiling"`
	// EnableLeaderElection enables leader election for controller manager
	EnableLeaderElection bool `yaml:"enable-leader-election" flag:"enable-leader-election" env:"ENABLE_LEADER_ELECTION" usage:"Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager." group:"General"`
	// EnableCRMetrics controls whether exposing the CR metrics is enabled
	EnableCRMetrics bool `yaml:"enable-cr-metrics" flag:"enable-cr-metrics" env:"ENABLE_CR_METRICS" usage:"Controls whether exposing the CR metrics is enabled" group:"Metrics, health, and profiling"`
	// CreateServiceMonitorOperatorMetrics creates a ServiceMonitor for the operator metrics
	CreateServiceMonitorOperatorMetrics bool `yaml:"create-service-monitor-operator-metrics" flag:"create-sm-operator-metrics" env:"CREATE_SM_OPERATOR_METRICS" usage:"Create a ServiceMonitor for the operator metrics" group:"Metrics, health, and profiling"`
	// WebhookPort is the port the webhook endpoint binds to.
	WebhookPort int `yaml:"webhook-port" flag:"webhook-port" env:"WEBHOOK_PORT" usage:"The port the webhook endpoint binds to." group:"General"`
	// FipsDisabledComponents are disabled collector components when operator runs on FIPS enabled platform
	FipsDisabledComponents string `yaml:"fips-disabled-components" flag:"fips-disabled-components" env:"FIPS_DISABLED_COMPONENTS" usage:"Disabled collector components when operator runs on FIPS enabled platform. Example flag value =receiver.foo,receiver.bar,exporter.baz" group:"OpenShift and FIPS"`
	// WatchNamespace is a comma-separated list of namespaces the operator should watch for
	// CustomResources. Empty string (the default) means watch all namespaces.
	WatchNamespace string `yaml:"watch-namespace" flag:"watch-namespace" env:"WATCH_NAMESPACE" usage:"Comma-separated list of namespaces the operator should watch for CustomResources. Empty means watch all namespaces." group:"General"`
	// TLS holds the TLS configuration of the controllers.
	TLS TLSConfig `yaml:"tls"`
	// ZapConfig holds the advanced Zap logging config
	Zap ZapConfig `yaml:"zap"`
	// EnableWebhooks enables the webhooks used by controllers.
	EnableWebhooks bool `yaml:"enable-webhooks" flag:"enable-webhooks" env:"ENABLE_WEBHOOKS" usage:"Enable webhooks for the controllers" group:"General"`
	// FeatureGates is a comma-separated list of feature gates to enable/disable.
	// Format: "gate1,gate2,-gate3" where - prefix disables the gate.
	// The --feature-gates CLI flag is registered separately in cmd/operator via featuregate.Flags; the generic walker skips it.
	FeatureGates string `yaml:"feature-gates" flag:"feature-gates" flagtype:"manual" env:"FEATURE_GATES" usage:"Comma-separated list of feature gates to enable/disable. Format: gate1,gate2,-gate3 where the - prefix disables the gate. The --feature-gates CLI flag is registered separately in cmd/operator." group:"Feature gates"`
	// Internal contains configuration that is propagated and cannot be accessed from the operator configuration.
	Internal Internal `yaml:"-"`
	// Instrumentation is the set of instrumentations to use if CRDs are not present
	Instrumentation v1alpha1.Instrumentation `yaml:"instrumentations"`
	// EnableInstrumentationCRDs enables looking for instrumentation CRDs.
	EnableInstrumentationCRDs bool `yaml:"enable-instrumentation-crds" flag:"-" env:"-" usage:"When false, use the embedded default instrumentation instead of looking for Instrumentation CRDs." group:"File-only keys"`
	// ProxyEnvVars holds the proxy environment variables (HTTP_PROXY, HTTPS_PROXY,
	// NO_PROXY — upper and lower case) captured from the operator's environment at
	// startup and propagated to all managed containers.
	ProxyEnvVars []corev1.EnvVar `yaml:"-"`
	// OpenShiftWebhookReplicas is the desired number of replicas for the standalone pod webhook deployment.
	// Only used on OpenShift with OLM where the pod webhook is deployed separately.
	// Set to 0 to disable the standalone webhook (webhook runs in operator pod instead).
	// Set to 1 to disable HA but keep the standalone deployment.
	// Default is 2 for HA on OpenShift. Only scaling down (0 or 1) is supported via env var.
	OpenShiftWebhookReplicas int32 `yaml:"openshift-webhook-replicas" flag:"openshift-webhook-replicas" env:"OPENSHIFT_WEBHOOK_REPLICAS" usage:"Number of replicas for the standalone pod webhook deployment on OpenShift. Set 0 to disable." group:"General"`
}

// Internal contains configuration that is propagated and cannot be accessed from the operator configuration.
type Internal struct {
	// CreateRBACPermissions is true when the operator can create RBAC permissions for SAs running a collector instance. Autodetected.
	CreateRBACPermissions autoRBAC.Availability `yaml:"-"`
	// NativeSidecarSupport is set to true if the corresponding featuregate is enabled and the minimum required k8s version is met.
	NativeSidecarSupport bool `yaml:"native-sidecar-support"`
	// KubeAPIServerPort is the port of the Kubernetes API server discovered from EndpointSlices.
	KubeAPIServerPort int32 `yaml:"kube-api-server-port"`
	// KubeAPIServerIPs are the IPs of the Kubernetes API server discovered from EndpointSlices.
	KubeAPIServerIPs []string `yaml:"kube-api-server-ips"`
	// OperandTLSProfile holds the TLS profile to inject into operand (collector) configurations.
	// This is set at operator startup from the cluster's TLS security profile and is applied
	// during reconciliation when generating ConfigMaps. When the cluster TLS profile changes,
	// the operator restarts (via SecurityProfileWatcher) and all collectors are reconciled
	// with the new TLS settings.
	OperandTLSProfile components.TLSProfile `yaml:"-"`
	// APIServerEndpoints tracks the endpoints of the Kubernetes API server. It's set at operator startup, and is
	// used to restrict egress to the API server in NetworkPolicies.
	APIServerEndpoints *apiserverendpoints.Tracker `yaml:"-"`
}

// New constructs a new configuration.
func New() Config {
	v := version.Get()
	return Config{
		CollectorImage:                      fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:%s", v.OpenTelemetryCollector),
		ClusterObservabilityCollectorImage:  fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s:%s", v.OpenTelemetryCollector),
		CollectorConfigMapEntry:             defaultCollectorConfigMapEntry,
		EnableMultiInstrumentation:          true,
		EnableApacheHttpdInstrumentation:    true,
		EnableDotNetAutoInstrumentation:     true,
		EnableGoAutoInstrumentation:         false,
		EnableNginxAutoInstrumentation:      false,
		EnablePythonAutoInstrumentation:     true,
		EnableNodeJSAutoInstrumentation:     true,
		EnableJavaAutoInstrumentation:       true,
		TargetAllocatorImage:                fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:%s", v.TargetAllocator),
		OperatorOpAMPBridgeImage:            fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/operator-opamp-bridge:%s", v.OperatorOpAMPBridge),
		TargetAllocatorConfigMapEntry:       defaultTargetAllocatorConfigMapEntry,
		OperatorOpAMPBridgeConfigMapEntry:   defaultOperatorOpAMPBridgeConfigMapEntry,
		OpenShiftRoutesAvailability:         openshift.RoutesNotAvailable,
		PrometheusCRAvailability:            prometheus.NotAvailable,
		CertManagerAvailability:             certmanager.NotAvailable,
		TargetAllocatorAvailability:         targetallocator.NotAvailable,
		CollectorAvailability:               collector.NotAvailable,
		IgnoreMissingCollectorCRDs:          false,
		AutoInstrumentationJavaImage:        fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:%s", v.AutoInstrumentationJava),
		AutoInstrumentationNodeJSImage:      fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:%s", v.AutoInstrumentationNodeJS),
		AutoInstrumentationPythonImage:      fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:%s", v.AutoInstrumentationPython),
		AutoInstrumentationDotNetImage:      fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:%s", v.AutoInstrumentationDotNet),
		AutoInstrumentationGoImage:          fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:%s", v.AutoInstrumentationGo),
		AutoInstrumentationApacheHttpdImage: fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:%s", v.AutoInstrumentationApacheHttpd),
		AutoInstrumentationNginxImage:       fmt.Sprintf("ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:%s", v.AutoInstrumentationNginx),
		LabelsFilter:                        []string{},
		AnnotationsFilter:                   []string{constants.KubernetesLastAppliedConfigurationAnnotation},
		OpAmpBridgeAvailability:             opampbridge.NotAvailable,
		MetricsAddr:                         ":8443",
		MetricsSecure:                       true,
		MetricsTLSCertFile:                  "",
		MetricsTLSKeyFile:                   "",
		ProbeAddr:                           ":8081",
		WebhookPort:                         9443,
		FipsDisabledComponents:              "uppercase",
		TLS: TLSConfig{
			UseClusterProfile: false,
			ConfigureOperands: false,
			MinVersion:        "VersionTLS12",
			CipherSuites:      nil,
		},
		Zap: ZapConfig{
			MessageKey:  "message",
			TimeKey:     "timestamp",
			LevelKey:    "level",
			LevelFormat: "uppercase",
		},
		EnableWebhooks: true,
		Internal: Internal{
			CreateRBACPermissions: autoRBAC.NotAvailable,
			NativeSidecarSupport:  false,
		},
		EnableInstrumentationCRDs: true,
		OpenShiftWebhookReplicas:  defaultOpenShiftWebhookReplicas,
	}
}

func (c Config) String() string {
	b, _ := yaml.Marshal(c)
	return string(b)
}

func (c Config) ToStringMap() map[string]string {
	b, _ := yaml.Marshal(c)
	var m map[string]string
	_ = yaml.Unmarshal(b, &m)
	return m
}

func (c *Config) Apply(configFile string) error {
	if configFile != "" {
		if err := ApplyConfigFile(configFile, c); err != nil {
			return fmt.Errorf("failed to apply file config: %w", err)
		}
	}

	ApplyEnvVars(c)
	if err := ApplyCLI(c); err != nil {
		return fmt.Errorf("failed to apply cli config: %w", err)
	}

	return nil
}
