apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "opentelemetry.io/v1alpha1",
          "kind": "OpenTelemetryCollector",
          "metadata": {
            "name": "simplest"
          },
          "spec": {
            "config": "receivers:\n  jaeger:\n\nprocessors:\n  queued-retry:\n\nexporters:\n  logging:\n\npipelines:\n  traces:\n    receivers: [jaeger]\n    processors: [queued-retry]\n    exporters: [logging]\n"
          }
        }
      ]
    capabilities: Basic Install
  name: opentelemetry-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OpenTelemetryCollector is the Schema for the opentelemetrycollectors
        API
      displayName: OpenTelemetry Collector
      kind: OpenTelemetryCollector
      name: opentelemetrycollectors.opentelemetry.io
      specDescriptors:
      - description: Args is the set of arguments to pass to the OpenTelemetry Collector
          binary
        displayName: Args
        path: args
      - description: Config is the raw JSON to be used as the collector's configuration.
          Refer to the OpenTelemetry Collector documentation for details.
        displayName: Config
        path: config
      - description: Image indicates the container image to use for the OpenTelemetry
          Collector.
        displayName: Image
        path: image
      - description: Mode represents how the collector should be deployed (deployment
          vs. daemonset)
        displayName: Mode
        path: mode
      - description: Replicas is the number of pod instances for the underlying OpenTelemetry
          Collector
        displayName: Replicas
        path: replicas
      version: v1alpha1
  description: Placeholder description
  displayName: Opentelemetry Operator
  install:
    spec:
      deployments:
      - name: opentelemetry-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: opentelemetry-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: opentelemetry-operator
            spec:
              containers:
              - command:
                - opentelemetry-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: opentelemetry-operator
                image: quay.io/opentelemetry/opentelemetry-operator:v0.0.2
                imagePullPolicy: Always
                name: opentelemetry-operator
                resources: {}
              serviceAccountName: opentelemetry-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - opentelemetry-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          verbs:
          - get
        - apiGroups:
          - opentelemetry.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: opentelemetry-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - tracing
  - distributed tracing
  - monitoring
  - troubleshooting
  maintainers:
  - email: juraci.github@kroehling.de
    name: Juraci Paixão Kröhling
  maturity: alpha
  provider:
    name: OpenTelemetry
  replaces: opentelemetry-operator.v0.0.1
  version: 0.0.2
