# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. collector, target allocator, auto-instrumentation, opamp, github action)
component: collector

# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: "Add the ability to configure the Collector's Service, Headless Service, Monitoring Service and Extension Service"

# One or more tracking issues related to the change
issues: [4205]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  Introduces additional CRD options to configure and manage all the services deployed alongside the Collector.
  Each of the Service, Headless Service, Monitoring Service & Extension Service can now be individually Enabled/Disabled
  and the Name can be overridden.