# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. collector, target allocator, auto-instrumentation, opamp, github action)
component: auto-instrumentation

# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add support for detecting and reading environment variables from POD's ConfigMap resources.

# One or more tracking issues related to the change
issues: [1393, 1814]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  Now the auto-instrumentation will see the environment variables defined via POD's `env.valueFrom.configMapKeyRef` and
  `envFrom.configMapRef` fields, so the auto-instrumentation will be able to prevent overriding them, or it will be able
  to extend the existing definition.
