# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: breaking

# The name of the component, or a single word describing the area of concern, (e.g. collector, target allocator, auto-instrumentation, opamp, github action)
component: target allocator

# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Drop compatibility with older target allocator versions

# One or more tracking issues related to the change
issues: [1907]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  We've made a breaking change to the target allocator configuration in 0.93.0. This change removes operator 
  compatibility with target allocator versions older than that. Users running more recent target allocator versions
  are unaffected.
