# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. collector, target allocator, auto-instrumentation, opamp, github action)
component: rbac

# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: "Added RBAC permissions for config.extensions.k8s_observer."

# One or more tracking issues related to the change
issues:
  - 4113

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  Generating RBAC rules for the k8s_observer extension in the OpenTelemetry Collector when used in the operator.
  The change addresses the issue where the collector lacked necessary permissions to list and watch Kubernetes resources.
