# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. collector, target allocator, auto-instrumentation, opamp, github action)
component: target allocator, collector

# A brief description of the change. Surround your text with quotes ("") if it needs to start with a backtick (`).
note: "Enable mTLS between the TA and collector for passing secrets in the scrape_config securely"

# One or more tracking issues related to the change
issues: [1669]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  This change enables mTLS between the collector and the target allocator (requires cert-manager).
  This is necessary for passing secrets securely from the TA to the collector for scraping endpoints that have authentication.
