name: "Check Auto-Instrumentation Revision"

on:
  pull_request:
    paths:
      - "autoinstrumentation/**"
      - ".github/workflows/check-autoinstrumentation-revision.yaml"
      - ".github/workflows/scripts/check-autoinstrumentation-revision.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-revision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate autoinstrumentation revisions
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: ./.github/workflows/scripts/check-autoinstrumentation-revision.sh
