name: Markdown Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-link-check:
    permissions:
      pull-requests: write # required for posting review comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # equivalent cli: linkspector check
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@568ec8d29fa92b31fd9ea5381e155c51e922af83 # v1.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
