name: "Nightly End-to-end tests with contrib-dev"

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  issues: write

jobs:
  run-e2e-tests:
    uses: ./.github/workflows/e2e-reusable.yaml
    with:
      collector-image: "otel/opentelemetry-collector-contrib-dev:latest"

  retry-on-failure:
    needs: [run-e2e-tests]
    if: failure()
    uses: ./.github/workflows/e2e-reusable.yaml
    with:
      collector-image: "otel/opentelemetry-collector-contrib-dev:latest"

  create-issue-on-failure:
    runs-on: ubuntu-latest
    needs: [run-e2e-tests, retry-on-failure]
    if: always() && (needs.run-e2e-tests.result == 'failure' && needs.retry-on-failure.result == 'failure')
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      
      - name: Create issue on test failure
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            // Get team members
            let approvers = [];
            try {
              const teamMembers = await github.rest.teams.listMembersInOrg({
                org: 'open-telemetry',
                team_slug: 'operator-approvers'
              });
              approvers = teamMembers.data.map(member => `@${member.login}`);
            } catch (error) {
              console.log('Could not fetch team members:', error.message);
              approvers = ['@open-telemetry/operator-approvers'];
            }
            
            const title = `Nightly e2e tests failed with contrib-dev collector`;
            const body = `
            ## Summary
            The nightly end-to-end tests using the latest \`otel/opentelemetry-collector-contrib-dev\` image have failed.
            
            ## Details
            - **Workflow run**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            - **Triggered on**: ${{ github.event_name }}
            - **Branch**: ${{ github.ref_name }}
            - **Commit**: ${{ github.sha }}
            - **Collector image**: otel/opentelemetry-collector-contrib-dev:latest
            
            ## Action Required
            This failure indicates a potential compatibility issue between the operator and the latest collector development build. Please investigate and determine if:
            
            1. This is a regression in the collector that needs to be reported upstream
            2. The operator needs updates to maintain compatibility
            3. This is a flaky test that should be re-run
            
            ## Next Steps
            - [ ] Review the failed test logs
            - [ ] Determine root cause (collector issue vs operator issue vs test flakiness)
            - [ ] Take appropriate action (fix operator, report collector bug, or re-run if flaky)
            - [ ] Close this issue once resolved
            
            /cc ${approvers.join(' ')}
            `;
            
            // Check if a similar issue already exists
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['e2e-failure', 'nightly', 'contrib-dev']
            });
            
            if (existingIssues.data.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['e2e-failure', 'nightly', 'contrib-dev', 'bug']
              });
              console.log('Created new issue for nightly e2e test failure');
            } else {
              console.log('Similar issue already exists, skipping issue creation');
            }