name: Ensure SHA Pinned Actions

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ensure-sha-pinned:
    name: Check for Tag Pinned Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@c5fc58bd0be7a4b94b73ce40250322d5b838a108 # main
        with:
          allowlist: |
            slsa-framework/slsa-github-generator
