name: Ensure SHA Pinned Actions

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ensure-sha-pinned:
    name: Check for Tag Pinned Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@3db98c0363e2fa5df3e1c4c471777a7c10b24cc9 # main
        with:
          allowlist: |
            slsa-framework/slsa-github-generator
