name: "Publish cp Auto-Instrumentation"

on:
  push:
    paths:
      - 'autoinstrumentation/cp/**'
      - '.github/workflows/publish-autoinstrumentation-cp.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'autoinstrumentation/cp/**'
      - '.github/workflows/publish-autoinstrumentation-cp.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        run: echo "VERSION=$(cat autoinstrumentation/cp/version.txt)" >> $GITHUB_ENV

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker image
        run: |
          cd autoinstrumentation/cp
          VERSION=${{ env.VERSION }} make docker

