name: "Publish simple-app"

on:
  workflow_dispatch:

env:
  PLATFORMS: linux/amd64
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/simple-app
  DOCKERHUB_IMAGE: ${DOCKERHUB_IMAGE:-otel/simple-app}

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      image: ${{ steps.release-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase image name
        run: echo "GHCR_IMAGE_LOWER=$(echo $GHCR_IMAGE | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set release image
        id: release-image
        run: echo "image=${GHCR_IMAGE_LOWER}" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: examples/simple-app
          file: examples/simple-app/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: false
          tags: ${{ env.GHCR_IMAGE_LOWER }}:test

  slsa-provenance:
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    needs: publish
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ${{ needs.publish.outputs.image }}
      digest: ${{ needs.publish.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
