name: "Publish Test E2E images"

on:
  push:
    paths:
      - 'tests/test-e2e-apps/**'
      - '.github/workflows/publish-test-e2e-images.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'tests/test-e2e-apps/**'
      - '.github/workflows/publish-test-e2e-images.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bridge-server:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: bridge-server
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  golang:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: golang
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  python:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: python
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  java:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: java
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  apache-httpd:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: apache-httpd
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  dotnet:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: dotnet
      platforms: linux/arm64,linux/amd64
  nodejs:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: nodejs
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  metrics-basic-auth:
    uses: ./.github/workflows/reusable-publish-test-e2e-images.yaml
    with:
      path: metrics-basic-auth
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le 
