name: "Publish artifacts"
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.3'
    - uses: actions/checkout@v1
    - name: "publishes the container images"
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        OPERATOR_VERSION: master
      run: ./.ci/publish-images.sh
