name: "Publish instrumentation E2E images"

on:
  push:
    paths:
      - 'tests/instrumentation-e2e-apps/**'
      - '.github/workflows/publish-autoinstrumentation-e2e-images.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'tests/instrumentation-e2e-apps/**'
      - '.github/workflows/publish-autoinstrumentation-e2e-images.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  golang:
    uses: ./.github/workflows/reusable-publish-autoinstrumentation-e2e-images.yaml
    with:
      language: golang
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  python:
    uses: ./.github/workflows/reusable-publish-autoinstrumentation-e2e-images.yaml
    with:
      language: python
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  java:
    uses: ./.github/workflows/reusable-publish-autoinstrumentation-e2e-images.yaml
    with:
      language: java
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  apache-httpd:
    uses: ./.github/workflows/reusable-publish-autoinstrumentation-e2e-images.yaml
    with:
      language: apache-httpd
      platforms: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
  dotnet:
    uses: ./.github/workflows/reusable-publish-autoinstrumentation-e2e-images.yaml
    with:
      language: dotnet
      platforms: linux/arm64,linux/amd64
