name: "Scorecard tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scorecard-tests:
    name: Scorecard tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kube-version:
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: "install kuttl and kind"
        run: ./hack/install-kuttl.sh

      - name: "start kind"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: make start-kind KUBE_VERSION=$KUBE_VERSION

      - uses: jpkrohling/setup-operator-sdk@v1.1.0
        with:
          operator-sdk-version: v1.13.1

      - name: "run scorecard test"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: make scorecard-tests
